### ISSUE TITLE
Weekly scrum - November 12

### ISSUE THREAD

**Issue by Andrei486** [Andrei486/sysc-4806-project#19]

**Comment by Andrei486** [comment]
Last week - set up Azure deployments (#1), added tests for CRUD repositories (#18, https://github.com/Andrei486/sysc-4806-project/pull/15).
Next week - TBD, perhaps work on implementing the other two kinds of questions in the model.
Blocks - nothing

**Comment by CamSommer** [comment]
Last Week  - Worked on creating models for the first use case, designed in a way to expand later. Added persistence to the model using CrudRepositories.
This week - TBD will discuss with the team tomorrow.
Blocking - Nothing currently Blocking progress.

**Comment by MiniEinsteinD** [comment]
Last week - Created the controllers and the initial views. Started up the README and finished most parts of it. 
Next week - TBD
Blocks - nothing

**Comment by Rayatk** [comment]
Last week - Updated the views (#17, #10) and helped in creating tests for ControllerStructure and Question (#20).
Next week - TBD with the team
Blocks - none

**Comment by burg1337** [comment]
Last Week - Created tests for Controller Structure and Question, reviewed most of the code for views and controller, helped create README
Next Week - TBD 
Blocks - Nothing at the moment
