### ISSUE TITLE
Weekly Scrum November 16th

### ISSUE THREAD

**Issue by CamSommer** [Andrei486/sysc-4806-project#35]
Please take a look at the comments below for everyone's summarized update.

**Comment by Andrei486** [comment]
Last week: implemented authentication/authorization using Spring Security
Next week: TBD
Blocked: nothing

**Comment by CamSommer** [comment]
Last Week - Started working on the survey results view page().
Next Week - Oral Presentation Prep, and finish the view for results page(#32).  
Blocks - Models for new question types(#21 #22  will need to be finished before the view can be finazlied.

**Comment by burg1337** [comment]
Last Week - Started working on implementing the multiple choice question, splitting up controller structure.
Next Week - Oral presentation preperation, finish implementing mc and maybe any other question for model (#21)
Blocks - Nothing (other than getting sick)

**Comment by Rayatk** [comment]
Last Week - Started working on implementing on allowing a survey to be deleted (#23).
Next Week - Oral presentation and finish the implementation above.
Blocks - Nothing to think of

**Comment by MiniEinsteinD** [comment]
Last Week - Started working on implementing the model for numerical question #22 
Next Week - Oral presentation and finish the implementation above.
Blocks - Nothing
