### ISSUE TITLE
Weekly Scrum November 23rd

### ISSUE THREAD

**Issue by Andrei486** [Andrei486/sysc-4806-project#41]

**Comment by Andrei486** [comment]
Last week: oral presentation prep, updated UI to show logged-in user (PR #36), implementing answering page for text/numerical questions (issue #26, PR #39).
Next week: continue issue #26, help others if needed
Blocking: nothing

**Comment by CamSommer** [comment]
Last Week - Mostly done results view (#32)but could not finish due to waiting on other issues.
Next Week - Finish results view then work on a feature to lock surveys from being answered (#42).
Blocks - Waiting on pull request for MCQ model to be merged to finish view.

**Comment by MiniEinsteinD** [comment]
Last week: Implemented numerical questions model #37 #22 
Next week: Implement the controller numerical question #22 
Blocked: BLACK FRIDAY SALES

**Comment by burg1337** [comment]
Last Week: Impleneted MCQuestion model and test #43 
Next week: Implent the controller and js as well as answering MCquestion #21 #24 
Blocks - nothing

**Comment by Rayatk** [comment]
Last week: Implemented the functionality of deleting a survey in controller and view, and verify users as survey author (#23)
Next week: Finish UMLs (#45)
Blocks: none
