### ISSUE TITLE
Weekly Scrum November 27

### ISSUE THREAD

**Issue by Andrei486** [Andrei486/sysc-4806-project#56]

**Comment by CamSommer** [comment]
Last week - Finished results view (#32). Helped with allowing users to answer MCQ (#25).
Next week - Allow survey authors to close and open a survey for answering (#42).
Blocking - None

**Comment by burg1337** [comment]
Last Week - Finished implementing MC question, updated README
Next Week - Working on issues for next sprint
Blocking - None

**Comment by MiniEinsteinD** [comment]
Last Week - Could not work any further on the code due to Black Friday
Next Week - Working on #54 
Blocking - None

**Comment by Rayatk** [comment]
Last Week - Complete deleting survey implementation and making diagrams (#23, #47, #45)
Next Week - Work on issues for next sprint.
Blocking - none
