### ISSUE TITLE
Weekly Scrum December 4

### ISSUE THREAD

**Issue by Andrei486** [Andrei486/sysc-4806-project#68]

**Comment by CamSommer** [comment]
Work Completed - Allow users to close surveys (#42), Did a quick fix for deleting surveys (#49).
Work to be done - Charts in results view (#54)
Blocking - Nothing

**Comment by Andrei486** [comment]
Last week: created PR (in review) for registering new users (issue #57, PR #66). Minor fixes (issues #60 and #58, PR #62).
Next week: letting the user add more options to MCQs (issue #67)
Blocking: none

**Comment by MiniEinsteinD** [comment]
Last week: I pushed the main changes to #33. 
Next week: Working on finalizing #33  and I will start working on one of the open issues. Most likely #55 (not sure yet)
Blocking: PANICKING FINAL WEEK 
![i9JNNvJ](https://github.com/Andrei486/sysc-4806-project/assets/76576485/83391aed-5346-4e97-9bef-7bc5a1696cd7)
